# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AC-remote' do
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AC-remote

  target 'AC-remoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AC-remoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
